name: Build
on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  bootstrap:
    strategy:
      matrix:
        os:
          - ubuntu
          - macos
        node-version:
          - '14.x'
          - '16.x'
          - '18.x'

    name: build
    runs-on: ${{ matrix.os }}-latest
    steps:
      - uses: actions/checkout@v4.2.2

      - uses: actions/setup-node@v4.1.0
        with:
          node-version: ${{ matrix.node-version }}

      - run: yarn install --frozen-lockfile

      - run: yarn build

      - run: yarn start
