name: Publish
on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1

      - uses: actions/setup-node@v3.8.1
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'
          scope: '@daliusd'

      - run: yarn install --frozen-lockfile

      - run: yarn build

      - run: yarn publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
